name: Convert MD to HTML

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'MD/**'

jobs:
  Convert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt -y update
          sudo apt -y install pandoc

      - name: Convert Updated/New MD to HTML
        run: |
          git diff --name-only HEAD^ HEAD | grep '^MD/.*\.md$' | while read md_file; do
            html_file="HTML/$(basename "$md_file" .md).html"
            pandoc -s -f markdown -t html "$md_file" -o "$html_file"
          done

      - name: Create Pull Request
        run : |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git checkout -b md-to-html-$(date +'%Y%m%d%H%M%S')
            git add HTML/*.html
            git commit -m "Add HTML files"
            git push origin md-to-html-$(date +'%Y%m%d%H%M%S')
            gh pr create --base main --title "Update HTML Files" --body "This PR updates the HTML files from the updated/add MD files."
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}