name: Convert MD to HTML

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'MD/**'

jobs:
  Convert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Pandoc
        run: |
          sudo apt -y update
          sudo apt -y install pandoc

      - name: Convert Updated/New MD to HTML
        run: |
          git diff --name-only HEAD^ HEAD | grep '^MD/.*\.md$' | while read md_file; do
            html_file="HTML/$(basename "$md_file" .md).html"
            pandoc -s -f markdown -t html "$md_file" -o "$html_file"
          done

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add HTML/*.html
          git commit -m "Add HTML files" -a
          git push