name: Convert MD to HTML

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'MD/**'

jobs:
   changed_files:
    runs-on: ubuntu-latest 
    name: List and upload changed files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37


      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if echo "$file" | grep -q "^MD/"; then
            echo "$file was changed"
            fi
          done

      - name: Install Pandoc
        run: |
          sudo apt -y update
          sudo apt -y install pandoc

      - name: Convert Updated/New MD to HTML
        run: |
          for md_file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $md_file == MD/*.md ]]; then
              html_file="HTML/$(basename "$md_file" .md).html"
              pandoc -s -f markdown -t html --template=template.html "$md_file" -o "$html_file"
            fi
          done

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add HTML/*.html
          git commit -m "Add HTML files" -a
          git push