name: Convert MD to HTML

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'MD/**'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Pandoc
        uses: docker://pandoc/core:2.9

      - name: Convert MD to HTML
        run: |
          for md_file in MD/*.md; do
            html_file="HTML/$(basename "$md_file" .md).html"
            pandoc -s -f markdown -t html "$md_file" -o "$html_file"
          done

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add HTML/*.html
          git commit -m "Add HTML files" -a
          git push