name: Convert HTML to MD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'TranslatedHTML/**'

jobs:
   changed_files:
    runs-on: ubuntu-latest 
    name: List and upload changed files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37


      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if echo "$file" | grep -q "^TranslatedHTML/"; then
            echo "$file was changed"
            fi
          done

      - name: Install Pandoc
        run: |
          sudo apt -y update
          sudo apt -y install pandoc

      - name: Convert Updated/New HTML to MD
        run: |
          for html_file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $html_file == TranslatedHTML/*.html ]]; then
              md_file="TranslatedMD/$(basename "$html_file" .html).md"
              pandoc -s -f html -t "$html_file" -o "$md_file"
            fi
          done

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add TranslatedMD/*.md
          git commit -m "Add MD files" -a
          git push